### ISSUE TITLE
TODO for Prototype

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/fontgoggles#2]
Specific things left to do:
- [x] Integrate main window in UI
- [x] add NSDocument subclass
- [x] integrate path c lib in `setup.py`, and `App/setup.py`
- [x] write and verify build instructions
- [x] setup CI with GitHub Actions
