### ISSUE TITLE
Misc Project File todo:

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/fontgoggles#21]
Save/restore:

- [x] typed text, text source reference
- [x] text handling state (bidi, etc)
- [x] visual alignment
- [x] feature state
- [x] VF location
- [x] size/margin/baseline
- [x] item size in font list
- [x] dimensions of SplitViews
- [x] BiDi checkbox
- [x] features/variation/options tab: which tab selected
