### ISSUE TITLE
TODO for Basic version

### ISSUE THREAD

**Issue by justvanrossum** [justvanrossum/fontgoggles#7]
- [x] selection of fonts
- ~[ ] feature/variations/options UI respond to font selection~ (see #18)
- [x] add bidi processing
- [x] make text entry, char list and glyph list reflect each others selection
- [x] left/right/center alignment
- [x] Use `ufo2ft` for feature building, see #5 
- [x] Feature compilation should report errors/warnings, see #6 
- [ ] Modify font list, by drag and drop reorder, dropping fonts on it, and deleting font items, see #13 and #12
